# Generated by Django 2.1.2 on 2018-11-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='name',
        ),
    ]
