# Generated by Django 2.1.2 on 2018-11-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_subscribers_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='email',
            new_name='your_email',
        ),
    ]
